version: '2'
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - 7002:8989
    environment:
      - PUID=1999
      - PGID=1999
      - TZ=Europe/Paris
    volumes:
      - /home/labobox/docker_apps/sonarr/config:/config
      - /home/labobox/docker_apps/rtorrentvpn/data:/tv
