version: '2'
services:
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    restart: always
    ports:
      - 7004:8181
    environment:
      - PUID=1999
      - PGID=1999
      - TZ=Europe/Paris
    volumes:
      - /home/labobox/docker_apps/tautulli/config:/config
      - /home/labobox/docker_apps/tautulli/logs:/logs:ro