version: '2'
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/labobox/docker_apps/portainer/data:/data
    environment:
      - TZ=Europe/Paris
